const products = [
    {
        id: 1,
        name: 'Dispenser Hot Cool Miyako WD-290 PHC',
        href: '#',
        imageSrc: 'https://cf.shopee.co.id/file/54feddb5d5c438a2ad0798566d6f5b64',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '350 Kupon',
        status: 'Tersedia',
    },
    {
        id: 2,
        name: 'Dispenser Hot Normal Miyako WD-189H / 350W',
        href: '#',
        imageSrc: 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/906/miyako_miyako-wd-190-ph-dispenser--hot--normal-_full04.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '250 Kupon',
        status: 'Habis',
    },
    {
        id: 3,
        name: 'Kipas Angin Stand Fan Miyako KAS-1618 B PL',
        href: '#',
        imageSrc: 'https://www.miyako.co.id/wp-content/uploads/2019/05/1-12.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '350 Kupon',
        status: 'Habis',
    },
    {
        id: 4,
        name: 'Magic Warmer Miyako MCM-528',
        href: '#',
        imageSrc: 'https://www.miyako.co.id/wp-content/uploads/2019/05/MCM-528-cover.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '350 Kupon',
        status: 'Habis',
    },
    {
        id: 5,
        name: 'Kompor Gas Rinnai RI-522C Dua Tungku',
        href: '#',
        imageSrc: 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/medium//108/MTA-54736785/oem_oem_full01.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '400 Kupon',
        status: 'Tersedia',
    },
    {
        id: 6,
        name: 'Miyako Mixer Stand Mixer SM-625 2in1 Garansi ',
        href: '#',
        imageSrc: 'https://id-test-11.slatic.net/p/099caa926bfc80857d65a974c6b77c22.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '350 Kupon',
        status: 'Habis',
    },
    {
        id: 7,
        name: 'Blender Miyako BL-101 PL',
        href: '#',
        imageSrc: 'https://cf.shopee.co.id/file/0bd13be651f815ef3a51519ac87e1fba',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '350 Kupon',
        status: 'Tersedia',
    },
    {
        id: 8,
        name: 'Galon Biasa',
        href: '#',
        imageSrc: 'https://www.kindpng.com/picc/m/422-4224246_round-5-gallon-water-container-hd-png-download.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '50 Kupon',
        status: 'Tersedia',
    },
    {
        id: 13,
        name: 'Air Galon',
        href: '#',
        imageSrc: 'https://www.kindpng.com/picc/m/422-4224246_round-5-gallon-water-container-hd-png-download.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '10 Kupon',
        status: 'Tersedia',
    },
    {
        id: 9,
        name: 'Galon Biasa + Air',
        href: '#',
        imageSrc: 'https://www.kindpng.com/picc/m/422-4224246_round-5-gallon-water-container-hd-png-download.png',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '60 Kupon',
        status: 'Tersedia',
    },
    {
        id: 10,
        name: 'Galon + Keran',
        href: '#',
        imageSrc: 'https://id-test-11.slatic.net/p/2e3e599ed4b84a4e716c0d6cd4f78fd1.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '60 Kupon',
        status: 'Tersedia',
    },
    {
        id: 11,
        name: 'Galon Keran + Air',
        href: '#',
        imageSrc: 'https://id-test-11.slatic.net/p/2e3e599ed4b84a4e716c0d6cd4f78fd1.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '70 Kupon',
        status: 'Tersedia',
    },
    {
        id: 12,
        name: 'Stand Mixer Miyako SM625 Pencampur LIMITED',
        href: '#',
        imageSrc: 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//97/MTA-12882705/miyako_miyako_full01.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        price: '250 Kupon',
        status: 'Tersedia',
    },
    
]

export default products 